services:
  api:
    build: .
    ports:
      - "8567:8080"
    env_file:
      - .env
    environment:
      # - USING_DOCKER=true
    restart: unless-stopped
    command: uvicorn app:app --host 0.0.0.0 --port 8080 --workers ${FASTAPI_WORKERS:-1}


  worker:
    build: .
    restart: unless-stopped
    depends_on:
      - redis
    command: rq worker --url redis://rq_redis:6379 task_manager --with-scheduler

  redis:
    container_name: rq_redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
